
default_platform(:android)

# To run the lane, execute the following command:
# bundle exec fastlane firebase_distribution


platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
        app: "1:4328141931:android:8bdcec6d8fec85952cad2e",
        firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
        android_artifact_type: "APK",
        android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
        testers: "hassan.shbib@mail.ru",
        release_notes: "Testing with Fastlane",
  )
  end
end